module.exports = {
    roles: [
        { label: 'admin' },
        { label: 'user' },
    ],
    statuses: [
        { label: 'drafted' },
        { label: 'finished' },
    ],
    conditions: [
        { label: 'new' },
        { label: 'very_good' },
        { label: 'correct' },
        { label: 'bad' },
    ],
    originCountries: [
        { label: 'Korea', image_url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/09/Flag_of_South_Korea.svg/2000px-Flag_of_South_Korea.svg.png' },
        { label: 'Japan', image_url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9e/Flag_of_Japan.svg/2000px-Flag_of_Japan.svg.png' },
        { label: 'China', image_url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/fa/Flag_of_the_People%27s_Republic_of_China.svg/2000px-Flag_of_the_People%27s_Republic_of_China.svg.png' },
    ],
    types: [
        { label: "action", is_nsfw: false },
        { label: "adventure", is_nsfw: false },
        { label: "comedy", is_nsfw: false },
        { label: "cooking", is_nsfw: false },
        { label: "doujinshi", is_nsfw: false },
        { label: "drama", is_nsfw: false },
        { label: "erotica", is_nsfw: true },
        { label: "fantasy", is_nsfw: false },
        { label: "gender_bender", is_nsfw: false },
        { label: "harem", is_nsfw: true },
        { label: "historical", is_nsfw: false },
        { label: "isekai", is_nsfw: false },
        { label: "josei", is_nsfw: false },
        { label: "manhua", is_nsfw: false },
        { label: "manhwa", is_nsfw: false },
        { label: "martial_arts", is_nsfw: false },
        { label: "mature", is_nsfw: true },
        { label: "mecha", is_nsfw: false },
        { label: "medical", is_nsfw: false },
        { label: "mistery", is_nsfw: false },
        { label: "one_shot", is_nsfw: false },
        { label: "pornographic", is_nsfw: true },
        { label: "psychological", is_nsfw: false },
        { label: "romance", is_nsfw: false },
        { label: "school_life", is_nsfw: false },
        { label: "sci_fi", is_nsfw: false },
        { label: "seinen", is_nsfw: false },
        { label: "shoujo", is_nsfw: false },
        { label: "shoujo_ai", is_nsfw: false },
        { label: "slice_of_life", is_nsfw: false },
        { label: "smut", is_nsfw: false },
        { label: "sports", is_nsfw: false },
        { label: "supernatural", is_nsfw: false },
        { label: "tragedy", is_nsfw: false },
        { label: "webtoons", is_nsfw: false },
        { label: "yaoi", is_nsfw: true },
        { label: "yuri", is_nsfw: true },
    ]
}